name: Continuous Integration

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  ci:
    runs-on: ubuntu-latest
    #strategy:
    #  max-parallel: 4
    #  matrix:
    #    python-version: [3.6, 3.7, 3.8]

    services:
      mariadb:
        image: mariadb
        env:
          MYSQL_ROOT_PASSWORD:
          MYSQL_DATABASE: zds_test
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=10s --health-retries=10

    steps:
    - uses: actions/checkout@v2

    - name: Configure sysctl limits for ElasticSearch
      run: |
      sudo swapoff -a
      sudo sysctl -w vm.swappiness=1
      sudo sysctl -w fs.file-max=262144
      sudo sysctl -w vm.max_map_count=262144

    - name: Run Elasticsearch
      uses: elastic/elastic-github-actions/elasticsearch@master
      with:
        stack-version: 5.5.2

    - name: Install
      run: ./scripts/install_zds.sh --answer-yes --detect-os-version --travis-output +full

    - name: Run Tests
      run: |
        source zdsenv/bin/activate
        make lint
        make test
