name: Continuous Integration

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  ci:

    runs-on: ubuntu-18.04
    #strategy:
    #  max-parallel: 4
    #  matrix:
    #    python-version: [3.6, 3.7, 3.8]

    steps:
    - name: Checkout Git repository
      uses: actions/checkout@v2

    #- name: Set up Python
    #  uses: actions/setup-python@v2
    #  with:
    #    python-version: 3.7

    - name: Funny stuff
      run: |
        echo ::group::Nice and clean
        echo Nice
        echo and
        echo clean
        echo ::endgroup::
        echo ::debug::Some debug
        echo ::warning::Some warning
        echo ::error::Some error

    - name: Install
      run: ./scripts/install_zds.sh --answer-yes --detect-os-version --travis-output +full

    - name: Run Tests
      run: |
        source zdsenv/bin/activate
        make lint
        make test


